### ISSUE TITLE
how use it

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [cmames/zramit#5]
I just want to hibernate, I installed it and did next next next. I am still not able to hibernate my kde neon. What is your advice please.

MERCI

**Comment by cmames** [comment]
ce n'est pas pour pouvoir hiberner mais pouvoir utiliser un swap zram même avec l'hibernation

**Comment by Konfekt** [comment]
Pourrait-on comparer zramit avec [zram-hibernate](https://github.com/gissf1/zram-hibernate)? Zram-hibernate désactive la zram avant d'hiberner pendant que zramit parait opérer dans une façon assez semblable?

**Comment by cmames** [comment]
Oui, zramit desactive le swap zram et bascule vers le swap disque avant d'hiberner, au réveil il réactive la zram
